#ifndef LIBPAS_CONTROLLER_H
#define LIBPAS_CONTROLLER_H

typedef enum {
	DEVICE_KIND_UNKNOWN=0,
	DEVICE_KIND_DSERIAL,
	DEVICE_KIND_MAX6675,
	DEVICE_KIND_MAX31855,
	DEVICE_KIND_DS18B20,
	DEVICE_KIND_SPWM,
	DEVICE_KIND_HPWM,
	DEVICE_KIND_DHT22,
	DEVICE_KIND_DHT22T,	//temperature
	DEVICE_KIND_DHT22H,	//humidity
	DEVICE_KIND_DS3231,
	DEVICE_KIND_TIMER,
	DEVICE_KIND_INDICATOR,
	DEVICE_KIND_MAX7219,
	DEVICE_KIND_TM1637,
	DEVICE_KIND_REGSTP,
	DEVICE_KIND_MATTER,
	DEVICE_KIND_SENSOR,
	DEVICE_KIND_EM
} DeviceKind;

#endif 
